name: Package Electron

on:
  push:
    branches:
      - master
      - develop
      - debug-build
  pull_request:
    paths:
      - 'app/**'
      - 'ember-electron/**'
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]

    steps:
    # Set up js package
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # install, test, build package
    - name: npm install
      shell: bash
      run: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        npm install
        cd electron-app && npm install
        cd ..

    # Build electron app package installers
    - name: package electron - windows
      run: npm run make

    # Upload installers to github action
    - name: upload win-installer
      uses: actions/upload-artifact@master
      with:
        name: win-installer
        path: electron-app/out/make/squirrel.windows/x64
